name: perf

on:
  push:
    branches:
      - master

jobs:
  # Run all unit tests.
  perf:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v2
      - name: Install build-essential
        run: apt-get update && apt-get install -y build-essential
      - name: Build
        run: make factorial
      - name: Run
        run: ./factorial
